version: '3.3'

services:
  restaurante-db:
    image: 'mysql:8.0.30'
    container_name: restaurante-db
    restart: always
    networks:
      - restaurante-network
    environment:
      MYSQL_DATABASE: 'restaurante'
      MYSQL_USER: 'restaurante'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secretroot'
    volumes:
        - ./:/mysql
    ports:
        - "3306:3306"
  restaurante-app:
    build: .
    container_name: restaurante-app
    command: mvn clean spring-boot:run -DskipTests -Dspring-boot.run.profiles=docker
    networks:
      - restaurante-network
    ports:
      - "8080:8080"
    depends_on:
      - restaurante-db
networks:
  restaurante-network:
    driver: "bridge"
